apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app-blue
  template:
    metadata:
      labels:
        app: web-app-blue
    spec:
      containers:
        - name: web-app-blue
          image: neysho/web-app-blue:1
          ports:
            - containerPort: 80
